export const HYDRATE_GENRES = 'HYDRATE_GENRES';
export const UPDATE_CURRENT_GENRE = 'UPDATE_CURRENT_GENRE';
export const HYDRATE_GAMES = 'HYDRATE_GAMES';
export const UPDATE_CURRENT_GAME = 'UPDATE_CURRENT_GAME';
export const HYDRATE_TAGS = 'HYDRATE_TAGS';
export const UPDATE_CURRENT_TAG = 'UPDATE_CURRENT_TAG';
export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_VIDEOS = 'UPDATE_VIDEOS';